### ISSUE TITLE
Error Adding Route

### ISSUE THREAD

**Issue by apstory** [riaansnyders/flexiapi#14]
I'm getting an error when adding a route to the workflow, please see attached screenshot below:

![api error 2](https://cloud.githubusercontent.com/assets/16451030/13954551/0279130e-f04a-11e5-903d-f18e087e0e53.PNG)

**Comment by riaansnyders** [comment]
Schduled for 24/03/2016

**Comment by riaansnyders** [comment]
@apstory Have you updated the solution to VS 2015? I unfortunately do not have a license for VS2015. I am currently using VS2013. What version are you using?

**Comment by apstory** [comment]
Yes I've upgraded to 2015, I've also upgraded the framework to 6 (4.6.1). As far as I can remember you should be able to open the solution if you have the latest update installed for VS2013. Can you please check.

**Comment by riaansnyders** [comment]
Thank you. I am updating my VS 2013. Wil let you know if this does not work. Will then switch to VS2015 Community Edition.

**Comment by riaansnyders** [comment]
Please note I had some issue with the update to VS2013. I am retrying this at the moment.

**Comment by riaansnyders** [comment]
After upgrading to VS2015 and re-adding packages to the upgraded solution I am now struggling with the below issue:

c:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\de89cff6\d7f784f3\App_Web_accountlockedout.cshtml.dae9cef9.jnj5sr5s.0.cs(28,78): error CS0433: The type 'System.Web.WebPages.WebPage' exists in both 'c:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Web.WebPages\v4.0_1.0.0.0__31bf3856ad364e35\System.Web.WebPages.dll' and 'c:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Web.WebPages\v4.0_2.0.0.0__31bf3856ad364e35\System.Web.WebPages.dll'

Once this is sorted I can hopefully move onto fixing the actual issue logged.

**Comment by riaansnyders** [comment]
Please check. This should work fine. Please make sure a valid service end point has been added to a service before adding workflow.

**Comment by riaansnyders** [comment]
Please provide any feedback with regards to this issue or any others logged (I don't see any other assigned tasks on VS online either - can I see this as signed off?).

**Comment by apstory** [comment]
Hi Riaan, I'll test first thing tomorrow morning.

**Comment by apstory** [comment]
Looks good thanks Riaan.

**Comment by riaansnyders** [comment]
Thanks @apstory.Are there any other issues / problems? Do you have a status on testing as I would like to get sign off, else please let me know if you need my assistance with other project parts.

**Comment by apstory** [comment]
Testing is basically complete from my side - no other issues
