### ISSUE TITLE
RequestType in Routing.Workflow

### ISSUE THREAD

**Issue by apstory** [riaansnyders/flexiapi#15]
What is the RequestType column used for in the Routing.Workflow table?

**Comment by riaansnyders** [comment]
Scheduled to comment of 23/03/2016

**Comment by riaansnyders** [comment]
This column stores the type of request or method that is being actioned. For example - if brokerA is doing a "Claim" service call we must route to service A

"Claim" = the RequestType.

Logically this passed in the method of the service to the rules engine to find a match and should always match the name of the method / service.
